Add recommendations
RomanLuperkal/java-filmorate pull request #11
Opened 2022-11-07 13:33 UTC by RomanLuperkal

add-recommendations

2022-11-09 08:27 UTC, alekseybch requested changes
Отлично выполненная работа, но есть предложение по поводу размещения метода в классе работы с репозиторием

2022-11-09 08:27 UTC, alekseybch commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    public List<Film> getRecommendations(int userId) {
Предлагаю вынести данный метод в UserService, так мы отделим логику от класса работы с репозиторием, на случай, если понадобится его сменить

2022-11-09 10:24 UTC, alekseybch approved these changes

2022-11-09 19:48 UTC, Krivinsky approved these changes
Замечаний и предложений нет, все хорошо.

2022-11-10 06:01 UTC, BolotovAnton approved these changes

2022-11-10 09:44 UTC, merged