feat: добавить функциональность «Поиск»
RomanLuperkal/java-filmorate pull request #12
Opened 2022-11-07 16:53 UTC by Krivinsky

Реализована функциональность «Поиск»

2022-11-08 07:06 UTC, alekseybch requested changes
Хорошая работа, но есть одно замечание с дублированием строчек кода

2022-11-08 07:06 UTC, alekseybch commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String directorName = titleDirector.toLowerCase();
Дублирует код из метода, так же с 353 строчкой

2022-11-08 07:28 UTC, BolotovAnton submitted a review, later dismissed
Красивый код)

2022-11-08 07:28 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(value = "query", defaultValue = "", required = false) String query,
Возможно, если есть признак defaultValue, то признак required = false не нужен

2022-11-08 07:28 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String directorName = titleDirector.toLowerCase();
А почему имя директора приводятся к нижнему регистру, а фильм с заглавной буквы? Иначе тесты постмана не проходятся?

2022-11-08 12:09 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmByTitle(String filmName) {
не совсем по адресу. но это не переопределение метода.

2022-11-08 12:15 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String directorName = titleDirector.toLowerCase();
Исправил

2022-11-08 12:15 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            @RequestParam(value = "query", defaultValue = "", required = false) String query,
Исправил

2022-11-08 12:26 UTC, alekseybch commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmByTitle(String filmName) {
Это реализация метода интерфейса

2022-11-08 14:20 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmByTitle(String filmName) {
Я здесь не могу поставить @Override т.к. в моей версии кода в interface FilmStorage не было метода Director makeDirector(). 
![image](https://user-images.githubusercontent.com/104010510/200588788-dba02f33-1a4b-4b68-9b21-aeac6c1d0fdd.png)

2022-11-08 14:24 UTC, alekseybch commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmByTitle(String filmName) {
getFilmByTitle - вот про этот метод, над ним Override. Директор приватный, он только для этой реализации, 332 строчка

2022-11-08 14:30 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmByTitle(String filmName) {
да да, понял, спасибо!!!))

2022-11-09 10:49 UTC, RomanLuperkal requested changes

2022-11-09 10:49 UTC, RomanLuperkal commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmByTitle(String filmName) {
Публичные методы пишутся перед приватными

2022-11-09 16:39 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List <Film> filmList;
Сделал

2022-11-09 16:40 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sqlQuery = "SELECT F.*, M.mpa_name FROM FILM AS F JOIN MPA AS M on F.MPA = M.MPA_ID WHERE F.NAME LIKE ? ";
Сделал

2022-11-09 16:41 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                "JOIN director AS d ON df.director_id = d.director_id WHERE d.DIRECTOR_NAME LIKE ? ";
Сделал

2022-11-09 16:46 UTC, Krivinsky commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmByTitle(String filmName) {
Исправил

2022-11-09 17:02 UTC, alekseybch approved these changes

2022-11-09 19:37 UTC, merged