Add feed
RomanLuperkal/java-filmorate pull request #16
Opened 2022-11-10 08:52 UTC by Malkis02

2022-11-10 10:29 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +            addToFeedAddFriend(userId, friendId);
Возможно, надо поменять местами строчки 92 и 93. А то, если будешь добавлять пользователя, который уже в друзьях, то событие попадет в ленту, что добавлен друг. А по факту будет исключение, что "Невозможно добавить в друзья пользователя который уже в друзьях"

2022-11-10 10:29 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        addToFeedDeleteFriend(userId, friendId);
То же самое. 118 строку в самый конец

2022-11-10 10:29 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "INSERT INTO feed (user_id, event_type, operation,entity_id,time_stamp) " +
Пробелов не хватает) Можно нажать Alt+Ctrl+L (автоматом в идее правит код)

2022-11-10 10:29 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
>          }
Тут то же самое, что я писал для UserDbStorage.
Review review = getReviewById(review.getReviewId());
addToFeedReviewUpdate(review.getReviewId());
        return review;
Чтобы событие в ленту записывалось только после того, как само событие точно произошло

2022-11-10 10:29 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        addToFeedReviewDelete(reviewId);
То же самое. 84ю строку в конец

2022-11-10 10:29 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            addToFeedAddLike(userId, filmId);
Поменять местами 229 и 230 строчки. Смотри комментарии к UserDbStorage

2022-11-10 10:29 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        addToFeedDeleteLike(userId, filmId);
То же самое, в конец, 251ю строку

2022-11-11 05:06 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewDbStorage.java
> +        addToFeedReviewDelete(reviewId);
String sql = "DELETE FROM REVIEWS WHERE REVIEW_ID = ?";
 jdbcTemplate.update(sql, reviewId);
addToFeedReviewDelete(reviewId);
}

2022-11-11 05:06 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        addToFeedDeleteFriend(userId, friendId);
Тут тоже бы в try catch.
try {
jdbcTemplate.update(sqlQuery, userId, friendId); // если запрос на дружбу есть, то удаляем его
addToFeedDeleteFriende(userId, friendId); // помещаем удаление в ленту событий
} catch {
................. // если запроса нет нет, кидаем исключение

2022-11-11 05:06 UTC, BolotovAnton commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
>                      "Лайка от пользователя с id=" + userId + " у фильма с id=" + friendId + " нет");
Тут напутано с сообщением ошибки. Метод про дружбу, сообщение про лайки

2022-11-11 08:07 UTC, RomanLuperkal requested changes

2022-11-11 08:07 UTC, RomanLuperkal commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        addToFeedDeleteLike(userId, filmId);
Если лайка нет, то исключение автоматом кинится в блоке if а вот поменять удаление лайков и запись в ленту нужно

2022-11-11 08:07 UTC, RomanLuperkal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
>                      "Лайка от пользователя с id=" + userId + " у фильма с id=" + friendId + " нет");
Это похоже мой косяк)

2022-11-11 08:07 UTC, RomanLuperkal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                .timestamp(rs.getDate("time_stamp"))
getDate заменить на getTimestamp, тогда время будет выводиться разное

2022-11-11 08:07 UTC, RomanLuperkal commented on src/main/resources/schema.sql
> +    event_type varchar,
Заменить на  - event_type enum('LIKE', 'REVIEW', 'FRIEND')
С оperation аналогично
В ER диаграмме соотв. подправить тоже

2022-11-11 08:25 UTC, RomanLuperkal requested changes

2022-11-11 08:25 UTC, RomanLuperkal commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
>      public List<User> getCommonFriends(Integer userId, Integer friendId) throws ResponseStatusException {
Публичные методы пишутся перед приватными

2022-11-11 12:15 UTC, RomanLuperkal approved these changes

2022-11-11 12:32 UTC, BolotovAnton approved these changes

2022-11-11 12:36 UTC, merged